feat: included up-to-date information
llama-risk/docs-gho pull request #1
Opened 2024-05-20 21:45 UTC by Aidasvenc

Some sections of current GHO documentation date back to before the stablecoin was launched. Therefore, an update of GHO documentation was performed to reflect the current state of the stablecoin as of May 2024.

List of changes:
- Changed some references like "will be" to a present tense.
- Clarified unclear statements.
- Updated the `Facilitators` section and added a subsection explaining GHO stability module.
- Clarified Governance structure and included an explanation covering GHO Liquidity Committee and GHO Stewards.

**Disclaimer:** these changes firstly need to be approved internally by Llama Risk team before escalating and merging them into the base repository.

2024-05-21 20:16 UTC, 0xValJohn requested changes

2024-05-21 20:16 UTC, 0xValJohn commented on docs/concepts/faq.md
> +Assets that are available in the Aave Protocol Lending Pool can be used to back GHO. The Ethereum V3 pool was first facilitator to launch and support minting (borrowing) GHO. It was possible because
missing "the" after "was"

2024-05-21 20:16 UTC, 0xValJohn commented on docs/concepts/faq.md
> +GHO introduces the concept of [Facilitators](../concepts/how-gho-works/gho-facilitators.md). A Facilitator (e.g., a protocol, an entity, etc.) has the ability to trustlessly mint (and burn) GHO token
change verbe tense here, "would have"

2024-05-21 20:16 UTC, 0xValJohn commented on docs/concepts/how-gho-works/gho-facilitators.md
> +### GHO Stability Module
change to be inline with the hackmd writeup

2024-05-21 20:16 UTC, 0xValJohn commented on docs/concepts/how-gho-works/gho-facilitators.md
> +Each Facilitator must be approved by [Aave Governance](https://governance.aave.com/). Before approving it, Aave Governance needs to determine and assign a Facilitator a specific Bucket capacity to bo
before approval (remove "it")

2024-05-21 20:16 UTC, 0xValJohn commented on docs/concepts/how-gho-works/gho-governance.md
> +### GHO Liquidity Committee
change to be inline with hackmd writeup

2024-05-21 20:16 UTC, 0xValJohn commented on docs/concepts/how-gho-works/gho-governance.md
> +GHO Stewards consists of members from Growth (ACI), Risk (ChaosLabs) and Finance (TokenLogic + karpatkey) Service Providers and utilise a 3 of 4 multi-sig.
need to check if it's still the case

2024-05-21 20:16 UTC, 0xValJohn commented on docs/concepts/how-gho-works/gho-implementation.md
> +After the launch, GHO stablecoin struggled to keep its peg. In order to counter these issues Aave's governance began closely monitoring GHO's market parameters and performance. Ever since then, Aave'
Not sure this is relevant to docs. remove

2024-05-24 20:36 UTC, Aidasvenc commented on docs/concepts/how-gho-works/gho-facilitators.md
> +### GHO Stability Module
Isn't this inline with other subsections? The subsection `Current facilitators` comprises of: `Aave v3 Ethereum Pool`, `FlashMinter`, `GHO Stability Module`.

2024-05-24 20:38 UTC, Aidasvenc commented on docs/concepts/how-gho-works/gho-governance.md
> +GHO Stewards consists of members from Growth (ACI), Risk (ChaosLabs) and Finance (TokenLogic + karpatkey) Service Providers and utilise a 3 of 4 multi-sig.
Yep, it is the current structure as per https://governance.aave.com/t/arfc-gho-stewards/16466

2024-05-28 20:56 UTC, merged